---
title: "Storage Change Anlaysis"
author: "Laura Condon"
date: "12/21/2018"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages('RColorBrewer') #Problem can't inesll packages
#library('RColorBrewer')
```

First setting up the run informaiton and directory paths
```{r domain_setup, echo = 'FALSE'}
source("/home/rstudio/CONUS1_Warming/R_scripts/PFB-ReadFcn.R")
runlist=c('Baseline','2Deg_Warming','4Deg_Warming')
ylist=4:7

#make a temporary data directory
localdir="/home/rstudio/data1"
datadir="/iplant/home/shared/avra/CONUS_1.0/Simulations/"
system(paste("mkdir ", localdir, sep=""))

#read in porosity
fpor_cyv="/iplant/home/shared/avra/CONUS_1.0/Simulations/Baseline/Raw_Outputs/CONUS.5layer.pfclm.PumpHS.run4.out.porosity.pfb"
fpor_l=paste(localdir,"Porosity.bin", sep="/")
system(paste('iget -KrfP', fpor_cyv, fpor_l, sep=" "))
porosity=readpfb(fpor_l, verbose=F)
porosity1=as.vector(porosity[,,5])
rm(porosity)

#Domain info 
nx=3342
ny=1888
nval=nx*ny

monthdays=c(31, 30, 31,31,28,31,30,31,30,31,31,30) #Number of days in the month for water year (i.e. starting in October)
monthends=cumsum(monthdays) #ending day of the month water year

# Latent Heat of vaporization 
lvap= 2.5104*10^6 # J/kg n- this is the value for 'hvap' in pfsimulator/clm/clm_varcon.F90 
#to convert from W/m2 to mm/hr
# w/m2= J/(s*m2) 
# LH (j/(s*m2)) / lvap (J/kg) = kg/(m2*s) /(1000 kg/m3) = m *1000 =mm
# so just multiply by 3600/lvap to get mm   
```

Loop through and calculate daily PET
```{r iget, echo = FALSE}
PET_ann=PET_mon=rep(0, nval)
mon=1
dayend=monthends[mon]
for (r in 1:1){
  print(paste("***Starting", runlist[r], "run****"))
  
  for(y in 2:3){
    print(paste("***Starting Year", ylist[y], "****"))
    
    for(d in 1:365){
		  print(paste("Day", d))
  
       #Get LH flux
		  fin=sprintf("%s%s/Processed_Outputs/Year%s/LH.daily.%03d.bin", datadir,runlist[r], ylist[y], d)
		  fout=sprintf("%s/%s.Year%s.LH.daily.%03d.bin", localdir,runlist[r], ylist[y],d)
		  print(fin)
		  print(fout)
		  system(paste('iget -Krfv', fin , fout, sep=" "))
		
		  # Read LH into R
		  to.read = file(fout, "rb")
		  header=readBin(to.read, integer(), endian = "little", size=4, n=3)
		  lh=readBin(to.read, double(), endian = "little", size=8, n=nval)
		  close(to.read)
		
		  #remove file to save space in app
		  system(paste('rm', fout, sep=" "))
		
		  #Get Soil Moisture
		  fin=sprintf("%s%s/Processed_Outputs/Year%s/SM.daily.%03d.bin", datadir,runlist[r], ylist[y], d)
		  fout=sprintf("%s/%s.Year%s.SM.daily.%03d.bin", localdir,runlist[r], ylist[y],d)
		  print(fin)
		  print(fout)
		  system(paste('iget -Krvf', fin , fout, sep=" "))
		
		  #Read Soil Moisture into R
		  to.read = file(fout, "rb")
		  header=readBin(to.read, integer(), endian = "little", size=4, n=3)
		  sm=readBin(to.read, double(), endian = "little", size=8, n=nval)
		  close(to.read)
		
		  #remove file to save space in app
		  system(paste('rm', fout, sep=" "))
	  
		  #convert lh to mm from daily average W/m2
      lhmm=lh/lvap*3600*24 
		
		  #Calculate beta and PET
      beta=PET=rep(0,nval)
      beta=((sm/porosity1)-0.2)/0.8
      beta[(beta<0)]=0 #getting rid of the negative values where the saturation is less than sres
      PET=lhmm/beta
    
      ##Write the daily Beta outputs and export to cyverse
      outvarlist=c("Beta", "PET_mm")
      for(ovar in 1:2){
        print(paste("Writing", outvarlist[ovar]))
        fname=sprintf("%s.Year%s.%s.daily.%03d.bin",runlist[r], ylist[y],outvarlist[ovar],d)
        fwrite=paste(localdir, fname, sep="/") #local path
        fcyv=sprintf("%s%s/Processed_Outputs/Year%s/%s", datadir,runlist[r], ylist[y],fname) #cyverse path
      
        #write 
        to.write = file(fwrite, "wb")
			    writeBin(as.integer(c(nx,ny,1)), to.write, size=4, endian="little")
			    writeBin(beta, to.write, size=8, endian="little")
	  	  close(to.write)
		  
	  	  #Transfer 
		    system(paste('icd', fpath, sep=" "))
		    system(paste("iput -f ", fwrite,  fcyv, sep=" "))
		  
		    #Remove locally
		    system(paste("rm", fwrite))
      }
    
    
      PET_mon=PET_mon+PET
      # If its the end of the month write out the monthly PET and reset
      if(d==dayend){
        fname=sprintf("%s.Year%s.PET_mm.monthly.%02d.bin",runlist[r], ylist[y],mon)
        print(paste("Day=", d, "Writing Month", mon,":", fname))
        fwrite=paste(localdir, fname, sep="/") #local path
        fcyv=sprintf("%s%s/Processed_Outputs/Year%s/%s", datadir,runlist[r], ylist[y],fname) #cyverse path
      
        #write 
        to.write = file(fwrite, "wb")
			   writeBin(as.integer(c(nx,ny,1)), to.write, size=4, endian="little")
			   writeBin(beta, to.write, size=8, endian="little")
	    	close(to.write)
		  
	  	  #Transfer 
		    system(paste('icd', fpath, sep=" "))
		    system(paste("iput -f ", fwrite,  fcyv, sep=" "))
		  
		    #Remove locally
		    system(paste("rm", fwrite))
		  
		    #Reset the monthly PET
		    PET_mon=rep(0,nval)
		    mon=mon+1
		    dayend=monthends[mon]
      
      }
    
      PET_ann=PET_ann+PET
  
  } #end for d

  ##Write the annual PET outputs and export to cyverse
  print(paste("Writing", outvarlist[ovar]))
  fname=sprintf("%s.Year%s.PET_mm.yearly.bin",runlist[r], ylist[y], d)
  fwrite=paste(localdir, fname, sep="/") #local path
  fcyv=sprintf("%s%s/Processed_Outputs/Year%s/%s", datadir,runlist[r], ylist[y],fname) #cyverse path
  #write Beta
  to.write = file(fwrite, "wb")
  writeBin(as.integer(c(nx,ny,1)), to.write, size=4, endian="little")
  writeBin(beta, to.write, size=8, endian="little")
  close(to.write)
  #Transfer Beta
  system(paste('icd', fpath, sep=" "))
  system(paste("iput -f ", fwrite,  fcyv, sep=" "))
  
  #Remove locally
  system(paste("rm", fwrite))
  
  } #end for y
} #end for r

```
